### ISSUE TITLE
Create logos for each project

### ISSUE THREAD

**Issue by AranKomat** [TheDuckAI/community-website#10]
We need a logo for each of the following (no text needed):

- Duck with or eating a donut (Duck OCR)
- Duck w/ or on bench or just bench (Duck Benchmark)
- Integral sign with Duck on the right hand side (Duck Minerva)
- Duck w/ a computer (OMCAD)

**Comment by tomohiro-sawada** [comment]
Stable diffusion worked well for ARB logo. Can do likewise for the other projects as well.
