### ISSUE TITLE
Investigate free variant of Notion

### ISSUE THREAD

**Issue by AranKomat** [TheDuckAI/community-website#18]

**Comment by tomohiro-sawada** [comment]
Promising: 
[Answer_1.txt](https://github.com/TheDuckAI/community-website/files/12316675/Answer_1.txt)
[Answer.txt](https://github.com/TheDuckAI/community-website/files/12316677/Answer.txt)

**Comment by tomohiro-sawada** [comment]
clickup.com seems to be the only good option. Some reasons why: 
- [Pricing](https://clickup.com/pricing ). Free tier seems enough. 
- [Discord integration](https://help.clickup.com/hc/en-us/articles/6305687271575-Discord-integration)
- [Github Integration](https://clickup.com/integrations/github)
